### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [xant/libiomux#2]
I would like to point out that identifiers like "[`__IOMUX_H__`](https://github.com/xant/libiomux/blob/825e9e54faf7ee55c5e682f2733882fe5008f661/src/iomux.h#L8)" and "[`__iom`](https://github.com/xant/libiomux/blob/825e9e54faf7ee55c5e682f2733882fe5008f661/src/iomux.c#L48)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by xant** [comment]
this should have been fixed now
