### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [xant/libiomux#3]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/xant/libiomux/blob/5cdc56492281b4ff4a44c65cec3275d0a67099df/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by xant** [comment]
the project is way too small to justify spending time to introduce either autotools or cmake.
If you have time to "waste" and feel like providing a patch that's always welcome
